# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

before_install: make -f travis/Makefile prepare_environment

language: cpp
compiler:
  - gcc
  - clang

script: make -f travis/Makefile run-tests

# Performance regression test vs v23
continuous-performance:
  reference-commit: 3b9473f4731d0c911cc6934c86ce9e1db291c077
  script:
    - mkdir -p build-reference && cd build-reference && cmake .. && make

notifications:
  recipients:
    - simon.kagstrom@gmail.com
  email:
    on_success: change
    on_failure: always

