# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

before_install: make -f travis/Makefile prepare_environment

language: cpp
compiler:
  - gcc
  - clang

script: make -f travis/Makefile run-tests


notifications:
  recipients:
    - simon.kagstrom@gmail.com
  email:
    on_success: change
    on_failure: always

